name: Build & deploy release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Set version to release
        run: ./gradlew --no-daemon unSnapshotVersion

      - name: Commit release version
        run: ./gradlew --no-daemon commitVersion

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: build
          path: builds
